<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <Version>2.1.1.3</Version>
        <Nullable>disable</Nullable>
        <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
        <AssemblyName>CammyFrey</AssemblyName>
        <RootNamespace>Cammy</RootNamespace>
    </PropertyGroup>

</Project>
